services:
  postgres:
    image: postgres:latest
    container_name: postgres_c
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123454
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - "3000:3000"
    stdin_open: true
