name: Deploy to AWS EC2 Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: pwd
      run: pwd

    - name: ls
      run: ls

    - name: cd back one
      run: cd ..

    - name: pwd
      run: pwd

    - name: ls
      run: ls

    - name: cd in frontend
      run: cd frontend

    - name: pwd
      run: pwd

    - name: ls
      run: ls

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: SSH into EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.EC2_SSH_PORT }}
        script: |
          sudo pm2 restart all
          sudo ln -s -f /etc/nginx/sites-available/yomy.online /etc/nginx/sites-enabled/
          sudo systemctl reload nginx
