name: Deploy to AWS EC2 Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Pull latest , npm install , npm run build , restart PM2 and Nginx
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.EC2_SSH_PORT }}
        script: |
          cd /home/ubuntu/to-do-fullstack
          git pull
          cd /home/ubuntu/to-do-fullstack/frontend
          npm install
          npm run build
          sudo pm2 restart all
          sudo pm2 save
          sudo ln -s -f /etc/nginx/sites-available/yomy.online /etc/nginx/sites-enabled/
          sudo systemctl reload nginx
